name: 'Check console.log'
description: 'Checks for console.log in your codebase'
author: your-papa'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'
inputs:
  repo-token:
    description: 'Token for the repo'
    required: true
    default: ${{ github.token }}
outputs:
  foundLogs:
    description: 'console.logs and where they are found'
runs:
  using: node20
  main: dist/index.js
